### ISSUE TITLE
An example how to explain the factors

### ISSUE THREAD

**Issue by peterjuv** [datacarpentry/R-ecology#19]
Factor labels are hard to understand. Instead, levels could be explained using a simple example how to reorder them, see the code below:

day <- c("day1", "day5", "day10", "day1", "day5", "day10", "day10", "day1")
\# day10 comes second
fDay <- factor(days)
fDay
levels(fDay)
\# day10 comes last
fDayOrdered <- factor(days, levels=c("day1", "day5", "day10"))
fDayOrdered
levels(fDayOrdered)

**Comment by apawlik** [comment]
Thanks @peterjuv! After confusing the attendees at http://anenadic.github.io/2015-07-22-ljubljana on the matter of factors, I think it would be good to get some more examples that allow people (that may include the instructor herself) grasp the concept.

**Comment by fmichonneau** [comment]
Currently we have a full section (with examples and a challenge) about factors here: https://github.com/datacarpentry/R-ecology/blob/gh-pages/02-starting-with-data.Rmd#factors

What do you suggest to make it clearer?

**Comment by fmichonneau** [comment]
Please re-open if you have suggestions on how to make the section on factors clearer.
