### ISSUE TITLE
Update R lesson so that it uses dataset on figshare

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/R-ecology#3]
http://figshare.com/articles/Portal_Project_Teaching_Database/1314459

Moving this issue over from https://github.com/datacarpentry/datacarpentry/issues/128 following the closing of https://github.com/datacarpentry/datacarpentry/issues/117.

**Comment by lwasser** [comment]
This is good - just a note that this lesson seems to use the  "messy version" of the data just like python does:
Surveys column names
record_id month day year plot species sex wgt

in the figshare version
record_id month day year plot species_id sex wgt

https://github.com/datacarpentry/planning/issues/3

we also need to add links to the data downloads up front.
