### ISSUE TITLE
Solutions to challenges

### ISSUE THREAD

**Issue by apawlik** [datacarpentry/R-ecology#56]
Some solutions to challenges are missing (for example "What was the heaviest animal measured in each year? Return the columns year, species, and weight."). It would be good to have a file which includes them all and maybe named "solutions.R"? Currently some stuff is in "handout" (?) but that is not obvious to the instructors.

**Comment by fmichonneau** [comment]
I'm happy to fill in the missing answers to the challenges. Currently, answers are either directly below the challenges, or included as comments in the (R)markdown file (they can be seen when browsing the source of lessons, but not displayed on the rendered HTML pages).

I'd like to keep the answers close to the challenges to make sure that they don't get out of sync (which will inevitably happen if they are in a separate file).
