### ISSUE TITLE
Figshare has changed download links - need to update links to data in lesson

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/R-ecology#67]
It seems that Figshare has changed the download links. So the links to the data in this lesson are no longer correct.

This affects 

02-starting-with-data.Rmd
05-visualization-ggplot2.Rmd
CONTRIBUTING.md
index.md

combined.csv is now https://ndownloader.figshare.com/files/2292169
surveys.csv is https://ndownloader.figshare.com/files/2292172
plots.csv is https://ndownloader.figshare.com/files/3299474
species.csv is https://ndownloader.figshare.com/files/3299483

**Comment by tracykteal** [comment]
Also since they are now https URLs, download.csv and read.csv do not support acquiring the files directly. @karthik @fmichonneau thoughts on the best way to get files from the new FigShare URLs in R?

**Comment by fmichonneau** [comment]
yes, it looks like the download links have changed... 

Newer versions of R (since 3.2.2) can now support the https downloads directly so it shouldn't be an issue.

I'm proposing to change the URLs in PR #60 as it already covers a lot of material, and it will limit merge conflicts. Does that sound good?

**Comment by tracykteal** [comment]
Thanks @fmichonneau, yes that sounds good, and sorry for letting the PR sit. I'll review it tonight. 

We will also need to add in the installation notes that people should have 3.2.2 and it might also be nice to provide a note like "If you get an error saying https isn't supporting, you need version 3.2.2 or later, or alternatively you can download the file to your computer and then load it in to R"

**Comment by fmichonneau** [comment]
OK, that sounds good. I'll add this to the setup instructions.
